---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: load-watcher
  namespace: monitoring
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: load-watcher
  replicas: 1 # tells deployment to run 1 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: load-watcher
    spec:
      containers:
      - name: watcher
        image: chenw/load-watcher:latest
        env:
        - name: METRICS_PROVIDER_NAME
          value: prometheus
        ports:
        - containerPort: 2020
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: load-watcher
  namespace: monitoring
  labels:
    app: load-watcher
spec:
  ports:
  - name: http
    port: 2020
    protocol: TCP
    targetPort: 2020
  selector:
    app: load-watcher